enum class NimbleCallbackReason {
	UNKNOWN = 0,
	SUCCESS,
	DONE,
	CHARACTERISTIC_WRITE_FAILED,
	CHARACTERISTIC_FIND_FAILED,
	SERVICE_FIND_FAILED,
	STOP_CANCEL_FAILED,
	CONNECTION_FAILED,
	OTHER_FAILED,
	// 途中経過
	CONNECTION_START,
	CONNECTION_ESTABLISHED,
	DISCONNECT,
};

typedef void (*SimpleNimbleCallback)(NimbleCallbackReason);